api:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 50
  service:
    type: ClusterIP
    port: 80
  image:
    repository: yaront111/hiredscorehw123-api
    tag: latest

queue:
  replicaCount: 2
  autoscaling:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 50
  image:
    repository: yaront111/hiredscorehw123-queue
    tag: latest

rabbitmq:
  host: my-rabbitmq
  replicaCount: 1
  auth:
    username: user
    password: password

mongodb:
  mongodbRootPassword: rootpassword
  mongodbUsername: user
  mongodbPassword: password
  mongodbDatabase: pizza_db
  replicaSet:
    enabled: true
    useHostnames: true
    replicas:
      secondary: 2